[User] add user profile and add display_name
astrocamp/17th-TechEcho pull request #151
Opened 2024-09-14 18:22 UTC by sabina726

1. 新增了個人檔案介面
2. user model增加了nickname,display_name欄位
3. 如果沒有填寫暱稱的話，都顯示帳號名稱
4. 如果有填寫暱稱，那會顯示名字的地方都會變成暱稱
5. 在要顯示名字的地方加上`get_display_name`  如： `{{ answer.user.get_display_name }}`
6. 刪掉暱稱的話會變回帳號名

https://github.com/user-attachments/assets/394b5af8-bd36-464c-b909-7b94c8b54a22

2024-09-15 04:21 UTC, Double-T1 requested changes
多行的 html 標籤請以以下兩種方式寫。
最簡單的方式就是確定 vscode 可以正確判定收起。
有不少要改，我就不全部標記了。

<img width="790" alt="Screenshot 2024-09-15 at 12 18 21 PM" src="https://github.com/user-attachments/assets/332dbbed-7852-49c9-b942-044c43648eda">
<img width="828" alt="Screenshot 2024-09-15 at 12 18 36 PM" src="https://github.com/user-attachments/assets/f0be1460-fb16-4186-8c06-82857321e224">

2024-09-15 04:21 UTC, Double-T1 commented on answers/templates/answers/_answer.html
> +      >
</textarea> 要同行，{{ answer.content }} 要縮排

2024-09-15 04:21 UTC, Double-T1 commented on templates/layouts/navbar.html
> +            >
</a>

2024-09-15 04:21 UTC, Double-T1 commented on templates/layouts/navbar.html
> +            >
同上

2024-09-15 04:21 UTC, Double-T1 commented on templates/layouts/navbar.html
> +        >
</a> 同行

2024-09-15 04:21 UTC, Double-T1 commented on templates/layouts/navbar.html
> +        >
一樣

2024-09-15 04:21 UTC, Double-T1 commented on templates/layouts/navbar.html
> +            >
一樣

2024-09-15 08:25 UTC, imEudora approved these changes

2024-09-15 14:46 UTC, sabina726 commented on answers/templates/answers/_answer.html
> +      >
改好了

2024-09-15 14:46 UTC, sabina726 commented on templates/layouts/navbar.html
> +            >
改好了

2024-09-15 14:47 UTC, sabina726 commented on templates/layouts/navbar.html
> +            >
改好了

2024-09-15 14:47 UTC, sabina726 commented on templates/layouts/navbar.html
> +        >
改好了

2024-09-15 14:47 UTC, sabina726 commented on templates/layouts/navbar.html
> +            >
改好了

2024-09-15 23:29 UTC, Double-T1 approved these changes

2024-09-16 02:38 UTC, alextechtrek approved these changes

2024-09-16 03:53 UTC, buding033171 approved these changes

2024-09-16 05:32 UTC, merged