[Blogs]author nickname
astrocamp/17th-TechEcho pull request #170
Opened 2024-09-17 05:49 UTC by alextechtrek

2024-09-17 15:47 UTC, Double-T1 requested changes
留言很多，但最主要有兩個問題一定要改：
1. 用不到的 script 絕對不要留在 html 裡，另外你同的 cdn 掛 base 一次個字檔案又掛一次，除服了
2. fontawesome icon 沒有加到我們設定的 fontawesome.js 裡，所以選染不出來。


<img width="646" alt="Screenshot 2024-09-17 at 11 43 41 PM" src="https://github.com/user-attachments/assets/ccce977f-c994-4dd4-be75-f7d57dbc337b">
要是中文

2024-09-17 15:47 UTC, Double-T1 commented on blogs/templates/blogs/edit.html
> +    <form method="post" enctype="multipart/form-data" class="space-y-4">
enctype 是指 encryption type? 目標是為了在 form 裡面顯示 markdown 嗎？

2024-09-17 15:47 UTC, Double-T1 commented on blogs/templates/blogs/edit.html
> +<script>
為什麼要留空的 script ?

2024-09-17 15:47 UTC, Double-T1 commented on blogs/templates/blogs/edit.html
> +<link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
這是幹嘛用的？拔掉會怎樣？

2024-09-17 15:47 UTC, Double-T1 commented on blogs/templates/blogs/new.html
> +<!-- Include EasyMDE CSS and JS -->
同 edit.html。為什麼這裡需要這個？

2024-09-17 15:47 UTC, Double-T1 commented on blogs/templates/blogs/preview.html
> +    <input type="hidden" name="title" value="{{ form.title.value }}">
這裡塞這些值，是哪裡的 JS 會用到嗎？

2024-09-17 15:47 UTC, Double-T1 commented on blogs/templates/blogs/show.html
> +    <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="rounded-lg shadow">
現在 blog model 沒有 image 對嗎？所以現在是寫假的對嗎

2024-09-17 15:47 UTC, Double-T1 commented on blogs/urls.py
> +    path("image-upload/", views.image_upload, name="image_upload"),
上傳照片不用綁定 id 嗎？是大家上傳都放同一個地方嗎？

2024-09-17 15:47 UTC, Double-T1 commented on blogs/views.py
> +import bleach
bleach 跟 pillow 是否要二選一？

2024-09-17 15:47 UTC, Double-T1 commented on blogs/views.py
> +from django.core.files.storage import default_storage
ContentFIle 跟 default_storage 是幹嘛的

2024-09-17 15:47 UTC, Double-T1 commented on blogs/views.py
> +        blog.author_display_name = blog.author.get_display_name()
為什麼要blog model 另外開一個 field 寫，不直接需要時引用 blog.author.get_display_name() 就好？

2024-09-17 15:47 UTC, Double-T1 commented on blogs/views.py
> +    if blog.author != request.user:
這個應該可以在 131 行 直接寫 get_object_404(Blog, pk=pk, author=user) 就好了，不用再寫 133 到 135

2024-09-17 15:47 UTC, Double-T1 commented on blogs/views.py
> +    if blog.author != request.user:
跟 edit 一樣，多寫了

2024-09-17 15:47 UTC, Double-T1 commented on package.json
> +  "dev": "concurrently \"npx tailwindcss -i ./src/styles/style.css -o ./static/styles/style.css --watch\" \"esbuild ./src/scripts/app.js --bundle --outfile=./static/scripts/app.js --watch\" \"node --
為什麼要加 npx? 差在哪

2024-09-17 15:47 UTC, Double-T1 commented on pyproject.toml
> +bleach = "^6.1.0"
bleach 跟 pillow 差在哪

2024-09-17 15:47 UTC, Double-T1 commented on templates/layouts/base.html
> +  <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
這個應該可以不用掛 cdn，可以塞到 style.css 裡

2024-09-17 15:47 UTC, Double-T1 commented on templates/layouts/base.html
> +  <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
這個也是應該可以塞到 app.js 裡

2024-09-17 15:47 UTC, Double-T1 commented on users/templates/layouts/profile.html
> +              ><i class="fas fa-user mr-2"></i>
這是 fontawesome ，但你似乎沒有掛到 fontawesome.js 裡？你有試過可不可以 render 出來嗎？

2024-09-17 23:21 UTC, alextechtrek commented on blogs/templates/blogs/preview.html
> +    <input type="hidden" name="title" value="{{ form.title.value }}">
我把preview.html 拔了 
目前他在new and edit 的右邊

2024-09-17 23:23 UTC, alextechtrek commented on blogs/views.py
> +import bleach
**Pillow** 和 **Bleach** 是兩個不同的東西：

1. **Pillow**：Pillow 是 Python Imaging Library (PIL) 的一個分支，為 Python 提供影像處理的功能。它可以用來開啟、操作和儲存多種不同格式的圖片。開發人員通常使用它來進行圖片的調整大小、格式轉換、添加濾鏡等操作。

2. **Bleach**：Bleach 是一個用於 Python 的 HTML 消毒庫。它用來清理和消毒 HTML 內容，以防止像跨站腳本 (XSS) 攻擊這樣的安全風險。Bleach 允許開發人員從內容中刪除不需要或不安全的 HTML 標籤和屬性，使其在網站上顯示時更安全。

2024-09-17 23:26 UTC, alextechtrek commented on pyproject.toml
> +bleach = "^6.1.0"
Pillow 用於圖片處理，Markdown 用於格式化文本，Bleach 用於清理和消毒 HTML 內容。

2024-09-17 23:27 UTC, alextechtrek commented on templates/layouts/base.html
> +  <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
Ok

2024-09-17 23:32 UTC, alextechtrek commented on blogs/templates/blogs/edit.html
> +<link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
目前他有用 easy mde...
就 可以不用的字中間畫線的markdown
可是目前他和user profile 一樣會出現 ！ 和?with dotted 虛線的圈圈 那個bar

2024-09-17 23:36 UTC, alextechtrek commented on blogs/views.py
> +        blog.author_display_name = blog.author.get_display_name()
這個版還能出現nickname 
晚上一點多 就不知道用到哪 已經出現不了在blog index display nickname 被我搞爛了...
我在show.html 才看的到 nickname

2024-09-17 23:39 UTC, alextechtrek commented on users/templates/layouts/profile.html
> +              ><i class="fas fa-user mr-2"></i>
我這邊本來就沒有顯示掛到 是照本身user app 加的 上面也都沒有顯示掛到 除了你的小鈴鐺 有img

2024-09-18 04:47 UTC, alextechtrek commented on users/templates/layouts/profile.html
> +              ><i class="fas fa-user mr-2"></i>
Sinba 改那個part了 他那邊有

2024-09-18 04:48 UTC, alextechtrek commented on pyproject.toml
> +bleach = "^6.1.0"
i remove bleach keep pillow 
pillow 是user在用的

2024-09-18 05:09 UTC, alextechtrek commented on blogs/templates/blogs/edit.html
> +<link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
我拔掉了easyMDE

2024-09-18 05:10 UTC, alextechtrek commented on blogs/templates/blogs/edit.html
> +<script>
用掉了

2024-09-18 08:22 UTC, sabina726 approved these changes

2024-09-18 08:22 UTC, imEudora approved these changes

2024-09-18 08:31 UTC, alextechtrek commented on blogs/urls.py
> +    path("image-upload/", views.image_upload, name="image_upload"),
之後問Tony 開一個還是放一起和ｕｓｅｒ pic

2024-09-18 08:32 UTC, alextechtrek commented on blogs/views.py
> +    if blog.author != request.user:
現在寫那個加到後面會爆掉

2024-09-18 08:36 UTC, alextechtrek commented on blogs/views.py
> +from django.core.files.storage import default_storage
upload content directly in memory iwthout first writing it to a temporary file on disk.

2024-09-18 08:43 UTC, buding033171 approved these changes

2024-09-18 09:51 UTC, ttonylee approved these changes

2024-09-18 09:59 UTC, Double-T1 approved these changes

2024-09-18 09:59 UTC, merged