Issue/#20
astrocamp/17th-TechEcho pull request #22
Opened 2024-08-28 11:14 UTC by chixxyy

1.  新增navbar選單與首頁
2. 首頁中的搜尋框
3. 加入主題顏色
4. RWD 768<=

2024-08-28 11:58 UTC, ttonylee approved these changes

2024-08-28 15:27 UTC, ttonylee commented
poetry.lock file show merge conflict after this branch removing "django-debug-toolbar" package, 
but the conflict happened on "content-hash" part and it's normal, I leave the newer one hash-value and remove older one

2024-08-29 03:42 UTC, sabina726 commented on core/urls.py
settings 應該不用加

2024-08-29 03:44 UTC, sabina726 requested changes

2024-08-29 03:44 UTC, sabina726 commented on core/urls.py
settings 應該不用加

2024-08-29 03:45 UTC, imEudora requested changes

2024-08-29 03:45 UTC, imEudora commented on templates/layouts/base.html
> +            <a href="#" class="transition duration-300 ease-in-out hover:text-green-3">&copy; 服務條款</a>
版權宣告copyright建議改一下，聯絡我們、隱私政策、服務條款不用加copy
https://zanzan.tw/archives/30463

2024-08-29 03:45 UTC, imEudora commented on core/urls.py
> +from django.conf import settings
為什麼要import settings?

2024-08-29 03:49 UTC, alextechtrek approved these changes
👍🏻

2024-08-29 03:53 UTC, chixxyy commented on templates/layouts/base.html
> +            <a href="#" class="transition duration-300 ease-in-out hover:text-green-3">&copy; 服務條款</a>
我先推上去再解決

2024-08-29 03:54 UTC, Double-T1 approved these changes

2024-08-29 03:54 UTC, Double-T1 commented on core/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
這句應該不需要

2024-08-29 03:55 UTC, buding033171 approved these changes
Ok

2024-08-29 04:22 UTC, ttonylee approved these changes

2024-08-29 04:23 UTC, ttonylee commented on core/urls.py
already removed, please kindly review again, thx

2024-08-29 04:23 UTC, ttonylee commented on core/urls.py
> +from django.conf import settings
already removed, please kindly review again, thx

2024-08-29 04:30 UTC, imEudora approved these changes

2024-08-29 04:31 UTC, sabina726 approved these changes

2024-08-29 04:32 UTC, merged